name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Compile LLM Bot (Windows)
        run: deno compile --no-check --allow-all --target x86_64-pc-windows-msvc --output compiled/llm-bot.exe main.ts
        
      - name: Compile LLM Bot (Linux, x86)
        run: deno compile --no-check --allow-all --target x86_64-unknown-linux-gnu --output compiled/llm-bot.x86_64 main.ts
        
      - name: Upload LLM Bot Artifact (Windows)
        uses: actions/upload-artifact@v3.1.2
        with:
          name: llm-bot-windows
          path: compiled/llm-bot.exe
          
      - name: Upload LLM Bot Artifact (Linux)
        uses: actions/upload-artifact@v3.1.2
        with:
          name: llm-bot-linux
          path: compiled/llm-bot.x86_64
